include:
  - project: 'alchemy/infrastructure/gitlab-ci-config'
    file: '3p-library-build.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  AUTOBUILD_PACKAGE_NAME: nvapi
  AUTOBUILD_PACKAGE_BASE_DIR: autobuild-internal
  AUTOBUILD_PACKAGE_DIR: nvapi
  NO_LNX: 1